---
# tasks file for Lvm-role
---
- name: Ensure lvm2 is installed
  package:
    name: lvm2
    state: present

- name: Create physical volumes
  command: pvcreate {{ lvm_physical_volumes }}
  when: item is defined
  register: pv_creation
  ignore_errors: true

- name: Create volume group
  command: vgcreate {{ lvm_volume_group }} {{ item }}
  loop: "{{ lvm_physical_volumes }}"
  when: pv_creation.rc == 0 # Only create VG if PV creation was successful
  register: vg_creation
  ignore_errors: true     # Ignore errors if PV already exists

- name: Create logical volume
  command: lvcreate -n {{ lvm_logical_volume }} -L {{ lvm_size }} {{ lvm_volume_group }}
  register: lv_creation
  when: vg_creation.rc == 0  # Only create LV if VG creation was successful
  ignore_errors: true

- name: Format the logical volume
  filesystem:
    fstype: ext4
    dev: /dev/{{ lvm_volume_group }}/{{ lvm_logical_volume }}
  when: lv_creation.rc == 0  # Only create when LV  creation was successful

- name: Ensure /var/lib/docker is exists
  